### ISSUE TITLE
as an authenticated user, when i add items to my cart form separate restaurants, and i click on 'my order', i see all of my items sorted by restaurant

### ISSUE THREAD

**Issue by brettgrigsby** [brettgrigsby/supper_skip#44]

**Comment by rickbacci** [comment]
Going to create a restaurant index page for this as we discussed.

**Comment by rickbacci** [comment]
We are going to have to sit down and plan out these routes. In a branch i'm attempting to nest items under restaurant so we can link an item to a restaurant and it breaks a ton of tests.

We also cannot log in as  a new user and redirect to a restaurant from the root page. (meaning the restaurant show page isn't accessible). You can create a restaurant and it will redirect you to YOUR  restaurant, but not another.

These are major design decisions that we need to figure out today. Maybe I mis-understood what I was supposed to do, but this story is going to require us to plan a bit together.
